[package]
name = "oxidized"
version = "0.1.0"
authors = ["DanCodes <dan@dancodes.online>"]
edition = "2021"
publish = false

[workspace]
members = [".", "api", "service", "entity", "torrent", "migration", "config"]

[dependencies]
oxidized-api = { path = "api" }
