[package]
name = "oxidized-config"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
config = "0.14.0"
rocket = "0.5.0"
serde = "1.0.199"
serde_derive = "1.0.199"
