[package]
name = "oxidized-entity"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
path = "src/lib.rs"

[dependencies]
regex = "1.10.4"
rocket = { version = "0.5.0", features = ["json"] }
sea-orm = "1.0.0"
serde = "1.0.200"
serde_json = "1.0.116"
tokio = "1.37.0"
