[package]
name = "oxidized-entity"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
path = "src/lib.rs"

[dependencies]
rocket = { version = "0.5.0", features = ["json"] }
sea-orm = "0.12.15"
serde = "1.0.198"
serde_json = "1.0.116"
tokio = "1.37.0"
